# Generated by Django 5.2.4 on 2026-10-03 06:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('build', 'Синтетический корпус'), ('dailydialog', 'DailyDialog: полный цикл'), ('ingest', 'Импорт текстов / диалогов'), ('bank', 'Импорт QA-SRL Bank'), ('annotate', 'Аннотация корпуса'), ('questions', 'Генерация QA'), ('export', 'Экспорт SFT / BIO'), ('report', 'Отчёт и проверка корпуса'), ('validate', 'Валидация QA-SRL Bank'), ('roundtrip', 'Round-trip вопросов'), ('candidates', 'Поиск кандидатов'), ('lookup', 'Глагольные формы'), ('mining', 'Кандидаты в пул сущностей')], max_length=24)),
                ('config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('succeeded', 'Завершён'), ('failed', 'Ошибка'), ('cancelled', 'Отменён')], default='queued', max_length=16)),
                ('phase', models.CharField(default='Ожидание свободного слота', max_length=200)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(default=dict)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('slot', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('stop_requested', models.BooleanField(default=False)),
            ],
        ),
    ]
