# Generated by Django 5.2.4 on 2026-10-03 11:23

import re

from django.db import migrations, models


# Only UI-generated metadata is translated. Logs and corpus text stay verbatim.
PHASES = {
    "Ожидание свободного слота": "Waiting for an available slot",
    "В очереди": "Queued",
    "Выполняется": "Running",
    "Завершён": "Completed",
    "Ошибка": "Failed",
    "Отменён": "Cancelled",
    "DailyDialog: экспорт и проверка": "DailyDialog: export and validation",
    "Экспорт SFT": "Exporting SFT",
    "Экспорт BIO / BILOU": "Exporting BIO / BILOU",
    "Проверка целостности и утечек": "Checking integrity and leakage",
    "Подготовка": "Preparing",
    "DailyDialog: аннотация → QA → экспорт → проверка": "DailyDialog: annotation → QA → export → validation",
    "DailyDialog завершён": "DailyDialog completed",
    "Поиск кандидатов в пул": "Mining entity pool proposals",
    "Создание независимой копии корпуса": "Creating an independent copy of the corpus",
    "Генерация → аннотации → QA": "Generation → annotations → QA",
    "Импорт Bank → аннотации → QA": "Bank import → annotations → QA",
    "Импорт и дедупликация документов": "Importing and deduplicating documents",
    "Аннотация → QA": "Annotation → QA",
    "Генерация QA": "QA generation",
    "Сохранение версии": "Saving the dataset version",
    "Обработка завершена": "Processing complete",
    "Прерванный запуск": "Interrupted job",
    "Валидация QA-SRL Bank": "QA-SRL Bank validation",
    "Round-trip вопросов": "Question round-trip",
    "Поиск кандидатов": "Candidate extraction",
    "Глагольные формы": "Verb forms"
}
ERRORS = {
    "Воркер был прерван. Создайте новый запуск; результат может быть неполным.": "The worker was interrupted. Create a new job; the output may be incomplete.",
    "Воркер остановлен во время выполнения.": "The worker stopped during execution."
}


def translate_metadata(apps, schema_editor, *, reverse=False):
    jobs = apps.get_model('app_main', 'Job').objects.using(schema_editor.connection.alias)
    for field, mapping in (('phase', PHASES), ('error', ERRORS)):
        pairs = ((new, old) for old, new in mapping.items()) if reverse else mapping.items()
        for old, new in pairs:
            jobs.filter(**{field: old}).update(**{field: new})

    old_pattern = r'Процесс завершился с кодом (-?\d+)\. Подробности в логе\.'
    new_pattern = r'Process exited with code (-?\d+)\. See the log for details\.'
    prefix = 'Process exited with code ' if reverse else 'Процесс завершился с кодом '
    for job in jobs.filter(error__startswith=prefix).only('pk', 'error').iterator():
        match = re.fullmatch(new_pattern if reverse else old_pattern, job.error)
        if match:
            code = match[1]
            message = (f'Процесс завершился с кодом {code}. Подробности в логе.' if reverse else
                       f'Process exited with code {code}. See the log for details.')
            jobs.filter(pk=job.pk).update(error=message)


def forwards(apps, schema_editor):
    translate_metadata(apps, schema_editor)


def backwards(apps, schema_editor):
    translate_metadata(apps, schema_editor, reverse=True)



class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='job',
            name='operation',
            field=models.CharField(choices=[('build', 'Synthetic corpus'), ('dailydialog', 'DailyDialog: full pipeline'), ('ingest', 'Text / dialogue import'), ('bank', 'QA-SRL Bank import'), ('annotate', 'Corpus annotation'), ('questions', 'QA generation'), ('export', 'SFT / BIO export'), ('report', 'Corpus report and validation'), ('validate', 'QA-SRL Bank validation'), ('roundtrip', 'Question round-trip'), ('candidates', 'Candidate extraction'), ('lookup', 'Verb forms'), ('mining', 'Entity pool proposals')], max_length=24),
        ),
        migrations.AlterField(
            model_name='job',
            name='phase',
            field=models.CharField(default='Waiting for an available slot', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
    ]
